### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/nl.inversion.wunderground#16]
A crash occurred for your app (version 0.2.5) at Nov 4, 2016 6:13 AM (UTC).

Homey software version: 0.10.7

Crash report: 
    TypeError: Cannot read property 'relative_humidity' of undefined
    at null.<anonymous> (/app.js:479:72)
    at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:138:26)
    at Request.self.callback (/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by Inversion-NL** [comment]
TypeError: Cannot read property 'txt_forecast' of undefined
    at null.<anonymous> (/app.js:457:49)
    at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:138:26)
    at Request.self.callback (/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by Inversion-NL** [comment]
TypeError: Cannot read property 'relative_humidity' of undefined
    at null.<anonymous> (/app.js:529:55)
    at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:137:26)
    at Request.self.callback (/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
