### ISSUE TITLE
crash wu

### ISSUE THREAD

**Issue by satbopper** [Inversion-NL/nl.inversion.wunderground#18]
Homey 10.9 and WU 0.2.5
Since 10.9 i had two crashes of WU
Stack trace:

TypeError: Cannot read property 'relative_humidity' of undefined
at null.<anonymous> (/app.js:479:72)
at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:138:26)
at Request.self.callback (/node_modules/request/request.js:199:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/node_modules/request/request.js:1036:10)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
at emitNone (events.js:72:20)

Exit code: 1

Anyone else who got this

**Comment by Inversion-NL** [comment]
I've got more crashes like this one, see #16
