### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/nl.inversion.wunderground#19]
A crash occurred for your app (version 0.1.0) at Nov 19, 2016 1:50 PM (UTC).

Homey software version: 1.0.1

Crash report: 
    TypeError: Cannot read property 'count' of undefined
    at Object.self.appWarning (/app.js:324:17)
    at emitNone (events.js:72:20)
    at Object.emit (events.js:166:7)
    at /bootstrap.js:201:30
    at /bootstrap.js:148:6
    at Array.filter (native)
    at WriteStream.cb (/bootstrap.js:147:39)
    at emitNone (events.js:72:20)
    at WriteStream.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:481:14)

**Comment by Inversion-NL** [comment]
Old version, already fixed.
