### ISSUE TITLE
App crashes every time

### ISSUE THREAD

**Issue by Leliekevertje** [Inversion-NL/nl.inversion.wunderground#24]
App crashes every now and then, see below:

Stack trace:

TypeError: Cannot read property 'txt_forecast' of undefined
at null.<anonymous> (/app.js:457:49)
at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:138:26)
at Request.self.callback (/node_modules/request/request.js:199:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/node_modules/request/request.js:1036:10)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
at emitNone (events.js:72:20)

Exit code: 1
Exit signal: null

**Comment by Inversion-NL** [comment]
Already working on it:

https://github.com/Inversion-NL/nl.inversion.wunderground/issues/21
