### ISSUE TITLE
App just crashed

### ISSUE THREAD

**Issue by Nreall** [Inversion-NL/nl.inversion.wunderground#6]
Hi,

The App just crashed on my Homey with the following error:

Stack trace:

TypeError: Cannot read property 'relative_humidity' of undefined
at null.<anonymous> (/app.js:362:55)
at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:137:26)
at Request.self.callback (/node_modules/request/request.js:199:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/node_modules/request/request.js:1036:10)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)

Just to let you know, it worked correct for a few weeks.

**Comment by Inversion-NL** [comment]
Yes, I know but I'm a bit on a tight schedule the couple of weeks.
Sorry
